name: Validate Reusable Workflows

on:
  push:
    branches: [main, dev]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate YAML syntax
        run: |
          echo "Validating reusable workflow syntax..."
          for file in .github/workflows/*.yml; do
            if [ -f "$file" ]; then
              echo "Checking $file"
              # Basic YAML validation
              python3 -c "import yaml; yaml.safe_load(open('$file'))" || exit 1
            fi
          done
          echo "✅ All workflows have valid YAML syntax"
      
      - name: Check for workflow_call
        run: |
          echo "Verifying all workflows are reusable (workflow_call only)..."
          for file in .github/workflows/*.yml; do
            if [ -f "$file" ] && [[ "$file" != *"/validate.yml" ]]; then
              if ! grep -q "workflow_call:" "$file"; then
                echo "❌ Error: $file is not a reusable workflow"
                exit 1
              fi
            fi
          done
          echo "✅ All workflows are properly configured as reusable"